function maintextToEnglish() {
        document.getElementById("maintext").innerHTML = 'The <i>Coronavirus Kindness Project</i> was launched in April 2020 to track and visualize news stories of kindness and acts of humanity as the world collectively faces the COVID-19 pandemic. While we consume the barrage of information related to the pandemic, its predominantly negative nature may result in increased anxiety and take a toll on our mental health. However, stories of humanity and kindness shine through! The goal of this project is to cultivate and share those stories; to be a centralized location of the positivity, kindness, and humanity of our local, national, and global neighbours. <br>';
}

function maintextToSpanish() {
	document.getElementById("maintext").innerHTML = 'El <i>Coronavirus Kindness Project</i> se lanzó en abril de 2020 con el propósito de enfatizar actos de bondad en medio de la pandémia mundial que estamos atravesando. La mayoría de las noticias actuales son de índole negativo. Esto resulta en un aumento de ansiedad y puede afectar grandemente nuestra salud mental. Sin embargo, hay un sin número de actos positivos que ensenan nuestra humanidad colectiva y la bondad que todavía podemos tener. El objetivo de este proyecto es reunir estas historias en un lugar centralizado. De esta manera, podemos compartir estas historias de bondad a nivel local, nacional y global para brindar esperanza en medio de las dificultades.';
}

function maintextToFrench() {
	document.getElementById("maintext").innerHTML = "Le <i>Coronavirus Kindness Project</i> a été lancé en avril 2020 pour suivre et visualiser les nouvelles des actes de gentillesse et d'humanité alors que le monde fait face collectivement à la pandémie de COVID-19. Bien que nous consommions le flot d'informations liées à la pandémie, sa nature principalement négative peut entraîner une anxiété accrue et nuire à notre santé mentale. Cependant, des histoires d'humanité et de gentillesse transparaissent! Le but de ce projet est de cultiver et de partager ces histoires; d'être un emplacement centralisé de la positivité, de la gentillesse, et de l'humanité de nos voisins locaux, nationaux, et mondiaux.";
}

function testimonialtextToEnglish() {
	document.getElementById("testimonialext").innerHTML = "The <i>Coronavirus Kindness Project</i> will soon be collecting testimonial stories of acts of kindness amid the cornonavirus. If you have <b>given</b>, <b>received</b>, or <b>observed</b> an act of kindness during this global pandemic, we invite you to share it with us. By sharing your story, you may inspire others to engage in their own act of kindness, both locally and globally. Your testimonials may also contribute to an ongoing research project aimed at better understanding how acts of kindness arise and are spread during a global pandemic.<br><br><b>Would you like to share your story of kindness?</b><br><br><a href='' target='_blank'><button class='button'><b>Submit your Testimonal Here</b></button></a>&nbsp;&nbsp;&nbsp;<button class='button' onmouseover='testimonialtextToSpanish();' onmouseout='testimonialtextToEnglish();'><b>Espanol</b></button>&nbsp;&nbsp;&nbsp;<a href='https://kindness-amid-coronavirus.com/docs/CvKP-Testimonial-EN.pdf' target='_blank'><button class='button'><b>PDF [EN]</b></button></a>&nbsp;&nbsp;&nbsp;<a href='https://kindness-amid-coronavirus.com/docs/CvKP-Testimonial-ES.pdf' target='_blank'><button class='button'><b>PDF [ES]</b></button></a><br><br>If you have any questions about out project, please contact us at: <a href='mailto:coronaviruskindnessproject@gmail.com'>coronaviruskindnessproject@gmail.com</a>";
}

function testimonialtextToSpanish() {
        document.getElementById("testimonialtext").innerHTML = "El <i>'Coronavirus Kindness Project'</i> esta coleccionando testimonios de actos de bondad en medio del coronavirus. Si has <b>dado</b>, <b>observado</b> o <b>recibido</b> un acto de bondad durante esta pandemia global, lo invitamos a compartirlo con nosotros. Al compartir su testimonio, podrás inspirar a otros a participar en su propio acto de bondad, a nivel local o global. Sus testimonios podrían contribuir a un proyecto de investigación dirigido para comprender mejor como los actos de bondad surgen y se propagan durante una pandemia mundial.<br><br><b>¿Quisieras compartir su historia de un acto de bondad?</b><br><br><a href='' target='_blank'><button class='button'><b>Envié aquí</b></button></a>&nbsp;&nbsp;&nbsp;<button class='button' onmouseover='testimonialtextToSpanish();' onmouseout='testimonialtextToEnglish();'><b>Espanol</b></button>&nbsp;&nbsp;&nbsp;<a href='https://kindness-amid-coronavirus.com/docs/CvKP-Testimonial-EN.pdf' target='_blank'><button class='button'><b>PDF [EN]</b></button></a>&nbsp;&nbsp;&nbsp;<a href='https://kindness-amid-coronavirus.com/docs/CvKP-Testimonial-ES.pdf' target='_blank'><button class='button'><b>PDF [ES]</b></button></a><br><br>Si tienes alguna pregunta sobre este proyecto, por favor comuníquese con nosotros: <a href='mailto:coronaviruskindnessproject@gmail.com'>coronaviruskindnessproject@gmail.com</a>";
}
